window.glossarioData = {
  "voci": [
    { "id": 1, "parola": "AARONNE", "def": "Fratello di Mose e primo sommo sacerdote d'Israele.", "rif": "Esodo 28:1" },
    { "id": 2, "parola": "ABADDON", "def": "Termine ebraico che significa distruzione.", "rif": "Rivelazione 9:11" },
    { "id": 3, "parola": "ABDON", "def": "Uno dei giudici che governo Israele per otto anni.", "rif": "Giudici 12:13" },
    { "id": 4, "parola": "ABERRAZIONE", "def": "Pratica o idolo detestabile agli occhi di Dio.", "rif": "Geremia 7:30" },
    { "id": 5, "parola": "ABIA", "def": "Re di Giuda, figlio e successore di Roboamo.", "rif": "1 Re 14:31" },
    { "id": 6, "parola": "ABIATAR", "def": "Sommo sacerdote e figlio di Ahimelec.", "rif": "1 Samuele 22:20" },
    { "id": 7, "parola": "ABIGAIL", "def": "Moglie di Nabal che agi con prudenza verso Davide.", "rif": "1 Samuele 25:3" },
    { "id": 8, "parola": "ABISAI", "def": "Figlio di Zeruia e valoroso guerriero di Davide.", "rif": "1 Samuele 26:6" },
    { "id": 9, "parola": "ABISSO", "def": "Luogo di confino profondo o condizione di inattivita.", "rif": "Rivelazione 20:3" },
    { "id": 10, "parola": "ABNER", "def": "Capo dell'esercito di Saul.", "rif": "1 Samuele 14:50" },
    { "id": 11, "parola": "ABRAAMO", "def": "Patriarca fedele chiamato amico di Geova.", "rif": "Genesi 12:1" },
    { "id": 12, "parola": "ACAIA", "def": "Provincia romana della Grecia meridionale.", "rif": "Atti 18:12" },
    { "id": 13, "parola": "ACAN", "def": "Israelita che pecco prendendo il bottino di Gerico.", "rif": "Giosue 7:1" },
    { "id": 14, "parola": "ACCAD", "def": "Una delle citta fondate da Nimrod.", "rif": "Genesi 10:10" },
    { "id": 15, "parola": "ACHILA", "def": "Cristiano di Corinto, marito di Priscilla.", "rif": "Atti 18:2" },
    { "id": 16, "parola": "ADAMANTE", "def": "Pietra durissima, simbolo di ostinazione.", "rif": "Zaccaria 7:12" },
    { "id": 17, "parola": "ADAMO", "def": "Primo uomo creato da Dio.", "rif": "Genesi 2:7" },
    { "id": 18, "parola": "ADES", "def": "Soggiorno dei morti, corrispondente all'ebraico Sceol.", "rif": "Atti 2:31" },
    { "id": 19, "parola": "ADONIA", "def": "Figlio di Davide che tento di usurpare il trono.", "rif": "1 Re 1:5" },
    { "id": 20, "parola": "ADRAMMELEC", "def": "Dio degli assiri a cui sacrificavano i figli.", "rif": "2 Re 17:31" },
    { "id": 21, "parola": "ADULTERIO", "def": "Infedelta coniugale condannata dalla Legge.", "rif": "Esodo 20:14" },
    { "id": 22, "parola": "AGABO", "def": "Profeta cristiano che predisse una carestia.", "rif": "Atti 11:28" },
    { "id": 23, "parola": "AGAG", "def": "Re degli amalechiti risparmiato da Saul.", "rif": "1 Samuele 15:8" },
    { "id": 24, "parola": "AGAR", "def": "Serva di Sara e madre di Ismaele.", "rif": "Genesi 16:1" },
    { "id": 25, "parola": "AGGEI", "def": "Profeta che incoraggio la ricostruzione del tempio.", "rif": "Aggeo 1:1" },
    { "id": 26, "parola": "AGRIPPA", "def": "Erode davanti al quale Paolo pronuncio la sua difesa.", "rif": "Atti 25:13" },
    { "id": 27, "parola": "AI", "def": "Citta conquistata da Giosue dopo una sconfitta.", "rif": "Giosue 7:2" },
    { "id": 28, "parola": "ALABASTRO", "def": "Vasetto di pietra usato per conservare profumi.", "rif": "Marco 14:3" },
    { "id": 29, "parola": "ALFAEOMEGA", "def": "Titolo di Geova che indica l'inizio e la fine.", "rif": "Rivelazione 1:8" },
    { "id": 30, "parola": "ALFEO", "def": "Padre dell'apostolo Matteo o Levi.", "rif": "Marco 2:14" },
    { "id": 31, "parola": "ALLELUIA", "def": "Traslitterazione di lodate Iah.", "rif": "Salmo 104:35" },
    { "id": 32, "parola": "ALOE", "def": "Pianta aromatica usata per profumare i letti.", "rif": "Proverbi 7:17" },
    { "id": 33, "parola": "ALTARE", "def": "Struttura per offrire sacrifici o incenso.", "rif": "Genesi 8:20" },
    { "id": 34, "parola": "AMALECHITI", "def": "Popolo nomade discendente da Esau.", "rif": "Esodo 17:8" },
    { "id": 35, "parola": "AMASA", "def": "Nipote di Davide e capo dell'esercito di Assalonne.", "rif": "2 Samuele 17:25" },
    { "id": 36, "parola": "AMAZIA", "def": "Re di Giuda che inizio bene ma divenne idolatra.", "rif": "2 Re 14:1" },
    { "id": 37, "parola": "AMEN", "def": "Significa cosi sia o sicuramente.", "rif": "Deuteronomio 27:15" },
    { "id": 38, "parola": "AMMONITI", "def": "Discendenti di Lot e nemici di Israele.", "rif": "Genesi 19:38" },
    { "id": 39, "parola": "AMON", "def": "Dio principale di Tebe in Egitto.", "rif": "Geremia 46:25" },
    { "id": 40, "parola": "AMORREI", "def": "Potente tribu cananea che abitava le montagne.", "rif": "Genesi 10:16" },
    { "id": 41, "parola": "ANANIA", "def": "Discepolo che battezzo Saulo di Tarso.", "rif": "Atti 9:10" },
    { "id": 42, "parola": "ANDREA", "def": "Fratello di Simon Pietro e apostolo di Gesu.", "rif": "Giovanni 1:40" },
    { "id": 43, "parola": "ANGELO", "def": "Messaggero spirituale di Dio.", "rif": "Genesi 16:7" },
    { "id": 44, "parola": "ANIMA", "def": "La persona stessa o la vita di cui gode.", "rif": "Genesi 2:7" },
    { "id": 45, "parola": "ANNA", "def": "Profetessa ottantenne presente al tempio.", "rif": "Luca 2:36" },
    { "id": 46, "parola": "ANNAS", "def": "Ex sommo sacerdote che interrogo Gesu.", "rif": "Giovanni 18:13" },
    { "id": 47, "parola": "ANTICRISTO", "def": "Chi si oppone a Cristo o ai suoi insegnamenti.", "rif": "1 Giovanni 2:18" },
    { "id": 48, "parola": "ANTIOCHIA", "def": "Citta dove i discepoli furono chiamati cristiani.", "rif": "Atti 11:26" },
    { "id": 49, "parola": "APOLLO", "def": "Cristiano eloquente esperto nelle Scritture.", "rif": "Atti 18:24" },
    { "id": 50, "parola": "APOLLION", "def": "Nome greco dell'angelo dell'abisso; Distruttore.", "rif": "Rivelazione 9:11" },
    { "id": 51, "parola": "APOSTASIA", "def": "Abbandono o ribellione contro la vera adorazione.", "rif": "2 Tessalonicesi 2:3" },
    { "id": 52, "parola": "APOSTOLO", "def": "Inviato o messaggero scelto da Gesu.", "rif": "Matteo 10:2" },
    { "id": 53, "parola": "AQUILA", "def": "Marito di Priscilla e collaboratore di Paolo.", "rif": "Atti 18:2" },
    { "id": 54, "parola": "ARABIA", "def": "Vasta regione desertica visitata da Paolo.", "rif": "Galati 1:17" },
    { "id": 55, "parola": "ARAN", "def": "Luogo dove Abraamo soggiorno dopo aver lasciato Ur.", "rif": "Genesi 11:31" },
    { "id": 56, "parola": "ARARAT", "def": "Monti su cui si poso l'arca dopo il Diluvio.", "rif": "Genesi 8:4" },
    { "id": 57, "parola": "ARCANGELO", "def": "Capo degli angeli; titolo applicato a Michele.", "rif": "Giuda 9" },
    { "id": 58, "parola": "ARCADELPATTO", "def": "Cassa sacra che rappresentava la presenza di Dio.", "rif": "Esodo 25:10" },
    { "id": 59, "parola": "AREOPAGO", "def": "Collina di Marte ad Atene, sede di un tribunale.", "rif": "Atti 17:19" },
    { "id": 60, "parola": "ARETA", "def": "Re dei nabatei citato da Paolo.", "rif": "2 Corinti 11:32" },
    { "id": 61, "parola": "ARIMATEA", "def": "Citta di origine di Giuseppe, che seppelli Gesu.", "rif": "Matteo 27:57" },
    { "id": 62, "parola": "ARISTARCO", "def": "Macedone che accompagno Paolo nei suoi viaggi.", "rif": "Atti 19:29" },
    { "id": 63, "parola": "ARMAGHEDON", "def": "Guerra del gran giorno di Dio l'Onnipotente.", "rif": "Rivelazione 16:16" },
    { "id": 64, "parola": "ARNON", "def": "Torrente che segnava il confine con Moab.", "rif": "Numeri 21:13" },
    { "id": 65, "parola": "ARTASERSE", "def": "Re di Persia che fermo i lavori a Gerusalemme.", "rif": "Esdra 4:7" },
    { "id": 66, "parola": "ASA", "def": "Re di Giuda noto per la sua lotta all'idolatria.", "rif": "1 Re 15:9" },
    { "id": 67, "parola": "ASAF", "def": "Levita musicista e compositore di molti Salmi.", "rif": "1 Cronache 6:39" },
    { "id": 68, "parola": "ASDOD", "def": "Una delle cinque principali citta dei filistei.", "rif": "1 Samuele 5:1" },
    { "id": 69, "parola": "ASIA", "def": "Provincia romana dove si trovavano le sette congregazioni.", "rif": "Rivelazione 1:4" },
    { "id": 70, "parola": "ASKALON", "def": "Citta portuale filistea.", "rif": "Giudici 1:18" },
    { "id": 71, "parola": "ASSALONNE", "def": "Figlio di Davide che guido una rivolta.", "rif": "2 Samuele 13:1" },
    { "id": 72, "parola": "ASSIRIA", "def": "Potenza mondiale che conquisto il regno di Israele.", "rif": "2 Re 17:6" },
    { "id": 73, "parola": "ASTROLOGI", "def": "Persone che pretendono di predire il futuro dalle stelle.", "rif": "Matteo 2:1" },
    { "id": 74, "parola": "ATALIA", "def": "Regina usurpatrice che stermino la stirpe reale.", "rif": "2 Re 11:1" },
    { "id": 75, "parola": "ATENE", "def": "Centro culturale della Grecia visitato da Paolo.", "rif": "Atti 17:15" },
    { "id": 76, "parola": "AZELLA", "def": "Specie di volatile citata nelle leggi alimentari.", "rif": "Levitico 11:13" },
    { "id": 77, "parola": "BAAL", "def": "Dio cananeo della fertilita e dei cieli.", "rif": "Giudici 2:13" },
    { "id": 78, "parola": "BAALPEOR", "def": "Idolo moabita che sedusse gli israeliti.", "rif": "Numeri 25:3" },
    { "id": 79, "parola": "BABILONIA", "def": "Capitale dell'impero di Nabucodonosor.", "rif": "Geremia 50:1" },
    { "id": 80, "parola": "BALAAC", "def": "Re di Moab che cerco di far maledire Israele.", "rif": "Numeri 22:2" },
    { "id": 81, "parola": "BALAAM", "def": "Profeta che cerco di maledire Israele per denaro.", "rif": "Numeri 22:5" },
    { "id": 82, "parola": "BALSAMO", "def": "Olio aromatico curativo estratto da piante.", "rif": "Geremia 8:22" },
    { "id": 83, "parola": "BARABBA", "def": "Criminale liberato al posto di Gesu.", "rif": "Matteo 27:16" },
    { "id": 84, "parola": "BARAC", "def": "Condottiero che sconfisse Sisera sotto Debora.", "rif": "Giudici 4:6" },
    { "id": 85, "parola": "BARNABA", "def": "Compagno di Paolo noto come figlio della consolazione.", "rif": "Atti 4:36" },
    { "id": 86, "parola": "BARTOLOMEO", "def": "Apostolo identificato spesso con Natanaele.", "rif": "Matteo 10:3" },
    { "id": 87, "parola": "BARUC", "def": "Segretario e amico del profeta Geremia.", "rif": "Geremia 32:12" },
    { "id": 88, "parola": "BASCAN", "def": "Regione fertile nota per le sue querce e i tori.", "rif": "Salmo 22:12" },
    { "id": 89, "parola": "BATSHEBA", "def": "Moglie di Uria e poi di Davide; madre di Salomone.", "rif": "2 Samuele 11:3" },
    { "id": 90, "parola": "BATTESIMO", "def": "Immersione completa in acqua per simboleggiare la dedizione.", "rif": "Matteo 3:16" },
    { "id": 91, "parola": "BEELZEBUB", "def": "Nome dato a Satana, principe dei demoni.", "rif": "Matteo 12:24" },
    { "id": 92, "parola": "BEERSEBA", "def": "Citta al confine meridionale d'Israele.", "rif": "Genesi 21:31" },
    { "id": 93, "parola": "BELTASHASSAR", "def": "Nome babilonese dato al profeta Daniele.", "rif": "Daniele 1:7" },
    { "id": 94, "parola": "BENEDIZIONE", "def": "Favore divino o lode rivolta a Dio.", "rif": "Numeri 6:24" },
    { "id": 95, "parola": "BENIAMINO", "def": "Ultimo figlio di Giacobbe e di Rachele.", "rif": "Genesi 35:18" },
    { "id": 96, "parola": "BEREA", "def": "Citta dove i discepoli esaminavano le Scritture.", "rif": "Atti 17:10" },
    { "id": 97, "parola": "BERNICE", "def": "Sorella del re Agrippa II.", "rif": "Atti 25:13" },
    { "id": 98, "parola": "BETANIA", "def": "Villaggio di Lazzaro sul monte degli Ulivi.", "rif": "Giovanni 11:1" },
    { "id": 99, "parola": "BETEL", "def": "Citta della tribu di Efraim nota come casa di Dio.", "rif": "Genesi 28:19" },
    { "id": 100, "parola": "BETLEMME", "def": "Citta della Giudea dove nacque il Messia.", "rif": "Michea 5:2" },
    { "id": 101, "parola": "BETSAIDA", "def": "Citta d'origine di Pietro, Andrea e Filippo.", "rif": "Giovanni 1:44" },
    { "id": 102, "parola": "BILHA", "def": "Serva di Rachele e madre di Dan e Neftali.", "rif": "Genesi 29:29" },
    { "id": 103, "parola": "BITINIA", "def": "Regione dove lo spirito non permise a Paolo di andare.", "rif": "Atti 16:7" },
    { "id": 104, "parola": "BOAZ", "def": "Uomo di Betlemme che sposo Rut.", "rif": "Rut 2:1" },
    { "id": 105, "parola": "CAIFA", "def": "Sommo sacerdote che complotto per uccidere Gesu.", "rif": "Matteo 26:3" },
    { "id": 106, "parola": "CAINO", "def": "Primogenito di Adamo ed Eva e primo omicida.", "rif": "Genesi 4:1" },
    { "id": 107, "parola": "CALCEDONIO", "def": "Pietra preziosa che adorna le fondamenta della Nuova Gerusalemme.", "rif": "Rivelazione 21:19" },
    { "id": 108, "parola": "CALEB", "def": "Esploratore che porto un rapporto positivo su Canaan.", "rif": "Numeri 13:6" },
    { "id": 109, "parola": "CALVARIO", "def": "Vedi Golgota; luogo dell'esecuzione di Gesu.", "rif": "Luca 23:33" },
    { "id": 110, "parola": "CANA", "def": "Luogo del primo miracolo dell'acqua in vino.", "rif": "Giovanni 2:1" },
    { "id": 111, "parola": "CANAAN", "def": "Terra promessa ai discendenti di Abraamo.", "rif": "Genesi 12:5" },
    { "id": 112, "parola": "CANDELABRO", "def": "Arredo d'oro del tabernacolo con sette lampade.", "rif": "Esodo 25:31" },
    { "id": 113, "parola": "CAPERNAUM", "def": "Citta sul mar di Galilea sede del ministero di Gesu.", "rif": "Matteo 4:13" },
    { "id": 114, "parola": "CAPPADOCIA", "def": "Regione dell'Asia Minore centrale.", "rif": "Atti 2:9" },
    { "id": 115, "parola": "CARMELO", "def": "Promontorio dove Elia sfido i profeti di Baal.", "rif": "1 Re 18:19" },
    { "id": 116, "parola": "CEDRON", "def": "Torrente che scorre tra Gerusalemme e l'Oliveto.", "rif": "Giovanni 18:1" },
    { "id": 117, "parola": "CEFA", "def": "Nome aramaico dato a Simon Pietro.", "rif": "Giovanni 1:42" },
    { "id": 118, "parola": "CENTURIONE", "def": "Ufficiale dell'esercito romano al comando di 100 soldati.", "rif": "Matteo 8:5" },
    { "id": 119, "parola": "CESAREA", "def": "Citta portuale sede dei governatori romani.", "rif": "Atti 10:1" },
    { "id": 120, "parola": "CHETURA", "def": "Seconda moglie di Abraamo dopo la morte di Sara.", "rif": "Genesi 25:1" },
    { "id": 121, "parola": "CHISON", "def": "Torrente che travolse l'esercito di Sisera.", "rif": "Giudici 5:21" },
    { "id": 122, "parola": "CILICIA", "def": "Regione dell'Asia Minore dove si trovava Tarso.", "rif": "Atti 9:11" },
    { "id": 123, "parola": "CIPRO", "def": "Isola dove nacque Barnaba.", "rif": "Atti 4:36" },
    { "id": 124, "parola": "CIRCONCISIONE", "def": "Segno del patto tra Dio e Abraamo.", "rif": "Genesi 17:10" },
    { "id": 125, "parola": "CIRO", "def": "Re di Persia che libero gli ebrei da Babilonia.", "rif": "Esdra 1:1" },
    { "id": 126, "parola": "CLAUDIO", "def": "Imperatore romano che espulse i giudei da Roma.", "rif": "Atti 18:2" },
    { "id": 127, "parola": "CLEOPA", "def": "Uno dei due discepoli sulla via di Emmaus.", "rif": "Luca 24:18" },
    { "id": 128, "parola": "COLOSSI", "def": "Citta della Frigia a cui Paolo scrisse una lettera.", "rif": "Colossesi 1:2" },
    { "id": 129, "parola": "CONO", "def": "Misura di volume o forma geometrica.", "rif": "Glossario" },
    { "id": 130, "parola": "CORA", "def": "Levita che guido la ribellione contro Mose.", "rif": "Numeri 16:1" },
    { "id": 131, "parola": "CORINTO", "def": "Citta greca nota per la sua immoralita.", "rif": "Atti 18:1" },
    { "id": 132, "parola": "CORNELIO", "def": "Centurione romano, primo gentile convertito.", "rif": "Atti 10:1" },
    { "id": 133, "parola": "CRETA", "def": "Isola del Mediterraneo visitata da Paolo.", "rif": "Atti 27:7" },
    { "id": 134, "parola": "CRISPUS", "def": "Capo della sinagoga di Corinto che si converti.", "rif": "Atti 18:8" },
    { "id": 135, "parola": "CRISTO", "def": "Titolo di Gesu che significa l'Unto.", "rif": "Matteo 1:16" },
    { "id": 136, "parola": "CRONACHE", "def": "Libri biblici che narrano la storia dei re.", "rif": "Glossario" },
    { "id": 137, "parola": "DALMAZIA", "def": "Parte dell'Illirico visitata da Tito.", "rif": "2 Timoteo 4:10" },
    { "id": 138, "parola": "DAMARIS", "def": "Donna ateniese che divenne credente.", "rif": "Atti 17:34" },
    { "id": 139, "parola": "DAMASCO", "def": "Citta della Siria sulla via percorsa da Saulo.", "rif": "Atti 9:2" },
    { "id": 140, "parola": "DAN", "def": "Citta al confine settentrionale d'Israele.", "rif": "Giudici 20:1" },
    { "id": 141, "parola": "DANIELE", "def": "Profeta deportato a Babilonia noto per la sua integrita.", "rif": "Daniele 1:1" },
    { "id": 142, "parola": "DARIO", "def": "Nome di diversi re medi e persiani.", "rif": "Esdra 4:5" },
    { "id": 143, "parola": "DAVIDE", "def": "Secondo re d'Israele e scrittore di Salmi.", "rif": "1 Samuele 16:13" },
    { "id": 144, "parola": "DEBORA", "def": "Profetessa e giudice che aiuto Barac.", "rif": "Giudici 4:4" },
    { "id": 145, "parola": "DECADE", "def": "Periodo di dieci giorni o anni.", "rif": "Glossario" },
    { "id": 146, "parola": "DECAPOLI", "def": "Regione di dieci citta a est del Giordano.", "rif": "Matteo 4:25" },
    { "id": 147, "parola": "DELILA", "def": "Donna che tradi Sansone rivelando il suo segreto.", "rif": "Giudici 16:4" },
    { "id": 148, "parola": "DEMETRIO", "def": "Argentiere di Efeso che istigo una rivolta.", "rif": "Atti 19:24" },
    { "id": 149, "parola": "DEMONE", "def": "Creatura spirituale malvagia e ribelle a Dio.", "rif": "Matteo 7:22" },
    { "id": 150, "parola": "DERBE", "def": "Citta visitata da Paolo e Barnaba.", "rif": "Atti 14:20" },
    { "id": 151, "parola": "DESERTO", "def": "Luogo arido dove Israele vagammo per 40 anni.", "rif": "Esodo 16:1" },
    { "id": 152, "parola": "DIANA", "def": "Nome romano della dea greca Artemide.", "rif": "Atti 19:24" },
    { "id": 153, "parola": "DIAVOLO", "def": "Significa calunniatore; titolo di Satana.", "rif": "Rivelazione 12:9" },
    { "id": 154, "parola": "DILUVIO", "def": "Catastrofe idrica globale ai tempi di Noe.", "rif": "Genesi 7:6" },
    { "id": 155, "parola": "DINA", "def": "Figlia di Giacobbe e Lia.", "rif": "Genesi 30:21" },
    { "id": 156, "parola": "DIONISIO", "def": "Giudice dell'Areopago che divenne credente.", "rif": "Atti 17:34" },
    { "id": 157, "parola": "DIOTREFE", "def": "Cristiano ambizioso che non riceveva gli apostoli.", "rif": "3 Giovanni 9" },
    { "id": 158, "parola": "DISCEPOLO", "def": "Chi impara e segue gli insegnamenti di un maestro.", "rif": "Matteo 28:19" },
    { "id": 159, "parola": "DORCAS", "def": "Vedi Tabita; discepola che faceva vesti per i poveri.", "rif": "Atti 9:36" },
    { "id": 160, "parola": "EBAL", "def": "Monte su cui furono pronunciate le maledizioni.", "rif": "Giosue 8:33" },
    { "id": 161, "parola": "EBREO", "def": "Nome applicato ad Abramo e ai suoi discendenti.", "rif": "Genesi 14:13" },
    { "id": 162, "parola": "EBRON", "def": "Citta dove Davide regno per sette anni.", "rif": "2 Samuele 2:11" },
    { "id": 163, "parola": "EDIFICI", "def": "Costruzioni destinate ad abitazione o scopi sacri.", "rif": "Matteo 24:1" },
    { "id": 164, "parola": "EDOM", "def": "Regione montuosa a sud del Mar Morto.", "rif": "Genesi 36:8" },
    { "id": 165, "parola": "EFESO", "def": "Metropoli dell'Asia Minore nota per il tempio di Artemide.", "rif": "Atti 19:1" },
    { "id": 166, "parola": "EFOD", "def": "Grembiule sacerdotale su cui era posto il pettorale.", "rif": "Esodo 28:6" },
    { "id": 167, "parola": "EFRAIM", "def": "Secondo figlio di Giuseppe e nome di una tribu d'Israele.", "rif": "Genesi 41:52" },
    { "id": 168, "parola": "EGITTO", "def": "Potenza mondiale in cui Israele fu schiavo per secoli.", "rif": "Genesi 12:10" },
    { "id": 169, "parola": "EGLON", "def": "Re di Moab che oppresse Israele.", "rif": "Giudici 3:12" },
    { "id": 170, "parola": "EKRON", "def": "Citta filistea settentrionale.", "rif": "Giosue 13:3" },
    { "id": 171, "parola": "ELAM", "def": "Regione a est di Babilonia, discendenti di Sem.", "rif": "Genesi 10:22" },
    { "id": 172, "parola": "ELI", "def": "Sommo sacerdote e giudice che educo Samuele.", "rif": "1 Samuele 1:9" },
    { "id": 173, "parola": "ELIA", "def": "Profeta che sfido i sacerdoti di Baal.", "rif": "1 Re 17:1" },
    { "id": 174, "parola": "ELIMAS", "def": "Mago che cerco di ostacolare Paolo a Cipro.", "rif": "Atti 13:8" },
    { "id": 175, "parola": "ELISABETTA", "def": "Moglie di Zaccaria e madre di Giovanni Battista.", "rif": "Luca 1:5" },
    { "id": 176, "parola": "ELISEO", "def": "Successore del profeta Elia.", "rif": "1 Re 19:16" },
    { "id": 177, "parola": "ELIU", "def": "Giovane che consiglio Giobbe e i suoi amici.", "rif": "Giobbe 32:2" },
    { "id": 178, "parola": "ELKANA", "def": "Padre del profeta Samuele.", "rif": "1 Samuele 1:1" },
    { "id": 179, "parola": "ELUL", "def": "Nome post-esilico del sesto mese del calendario sacro.", "rif": "Neemia 6:15" },
    { "id": 180, "parola": "EMMANUELE", "def": "Titolo messianico che significa Con noi e Dio.", "rif": "Isaia 7:14" },
    { "id": 181, "parola": "EMMAUS", "def": "Villaggio vicino a Gerusalemme citato in Luca.", "rif": "Luca 24:13" },
    { "id": 182, "parola": "ENIGMI", "def": "Detti oscuri o domande difficili che richiedono intuito.", "rif": "Salmo 49:4" },
    { "id": 183, "parola": "ENOC", "def": "Uomo fedele che cammino con il vero Dio.", "rif": "Genesi 5:22" },
    { "id": 184, "parola": "ENOS", "def": "Figlio di Set, ai cui tempi si inizio a invocare il nome di Dio.", "rif": "Genesi 4:26" },
    { "id": 185, "parola": "EPICUREI", "def": "Filosofi seguaci di Epicuro che cercavano il piacere.", "rif": "Atti 17:18" },
    { "id": 186, "parola": "EPIFANIA", "def": "Manifestazione o apparizione di una divinita.", "rif": "Glossario" },
    { "id": 187, "parola": "EPISCOPO", "def": "Termine greco per sorvegliante o custode.", "rif": "Atti 20:28" },
    { "id": 188, "parola": "EREDE", "def": "Persona che riceve legalmente un'eredita o promessa.", "rif": "Romani 8:17" },
    { "id": 189, "parola": "ERESIA", "def": "Insegnamento che promuove divisioni nella congregazione.", "rif": "2 Pietro 2:1" },
    { "id": 190, "parola": "ERMES", "def": "Dio greco dei messaggi, confuso con Paolo a Listra.", "rif": "Atti 14:12" },
    { "id": 191, "parola": "ERMON", "def": "Monte innevato al confine settentrionale d'Israele.", "rif": "Salmo 133:3" },
    { "id": 192, "parola": "ERODE", "def": "Nome di una dinastia di re che governo sui giudei.", "rif": "Matteo 2:1" },
    { "id": 193, "parola": "ESILIO", "def": "Allontanamento forzato dalla propria patria.", "rif": "Ezechiele 1:1" },
    { "id": 194, "parola": "ESPIAZIONE", "def": "Copertura dei peccati per la riconciliazione con Dio.", "rif": "Levitico 16:30" },
    { "id": 195, "parola": "ESTASI", "def": "Stato di concentrazione intensa in cui si ricevono visioni.", "rif": "Atti 10:10" },
    { "id": 196, "parola": "ESTER", "def": "Regina ebrea che salvo il suo popolo dallo sterminio.", "rif": "Ester 2:7" },
    { "id": 197, "parola": "ETA", "def": "Periodo della vita o epoca storica specifica.", "rif": "Glossario" },
    { "id": 198, "parola": "ETIOPE", "def": "Abitante della regione a sud dell'Egitto.", "rif": "Atti 8:27" },
    { "id": 199, "parola": "ETIOPIA", "def": "Regione a sud dell'Egitto, nota anche come Cus.", "rif": "Atti 8:27" },
    { "id": 200, "parola": "EUFRATE", "def": "Grande fiume che bagnava Babilonia.", "rif": "Genesi 2:14" },
    { "id": 201, "parola": "EUNUCO", "def": "Uomo castrato o alto funzionario di corte.", "rif": "Matteo 19:12" },
    { "id": 202, "parola": "EVANGELIZZATORE", "def": "Chi annuncia o porta buone notizie.", "rif": "Atti 21:8" },
    { "id": 203, "parola": "EVIDENZA", "def": "Dimostrazione lampante di una realta non vista.", "rif": "Ebrei 11:1" },
    { "id": 204, "parola": "EXVOTO", "def": "Dono offerto a Dio in seguito a una promessa.", "rif": "Glossario" },
    { "id": 205, "parola": "FARAONE", "def": "Titolo regale dei sovrani d'Egitto.", "rif": "Esodo 5:1" },
    { "id": 206, "parola": "FARISEO", "def": "Membro di una setta giudaica nota per il rigorismo.", "rif": "Matteo 5:20" },
    { "id": 207, "parola": "FEDE", "def": "Sicura aspettativa di cose sperate.", "rif": "Ebrei 11:1" },
    { "id": 208, "parola": "FEDELTA", "def": "Qualita di chi e leale e costante verso Dio.", "rif": "Galati 5:22" },
    { "id": 209, "parola": "FENICIA", "def": "Regione costiera nota per Tiro e Sidone.", "rif": "Atti 11:19" },
    { "id": 210, "parola": "FESTA", "def": "Occasione di celebrazione gioiosa e sacra.", "rif": "Levitico 23:2" },
    { "id": 211, "parola": "FIGLIODELLUOMO", "def": "Titolo che sottolinea l'umanita del Messia.", "rif": "Matteo 8:20" },
    { "id": 212, "parola": "FILADELFIA", "def": "Citta dell'Asia lodata per la sua perseveranza.", "rif": "Rivelazione 3:7" },
    { "id": 213, "parola": "FILIPPI", "def": "Colonia romana in Macedonia sede di una congregazione.", "rif": "Atti 16:12" },
    { "id": 214, "parola": "FILISTEI", "def": "Popolazione nemica d'Israele stanziata sulla costa.", "rif": "Giudici 13:1" },
    { "id": 215, "parola": "FILOSOFIA", "def": "Ricerca della sapienza basata su ragionamenti umani.", "rif": "Colossesi 2:8" },
    { "id": 216, "parola": "FINEDELSISTEMA", "def": "Conclusione dell'attuale ordine mondiale malvagio.", "rif": "Matteo 24:3" },
    { "id": 217, "parola": "FIRMA", "def": "Marchio o sottoscrizione a convalida di un documento.", "rif": "Giobbe 31:35" },
    { "id": 218, "parola": "FONDAMENTO", "def": "Base solida su cui si poggia un edificio o una fede.", "rif": "1 Corinti 3:11" },
    { "id": 219, "parola": "FORNICAZIONE", "def": "Rapporti sessuali illeciti fuori dal matrimonio.", "rif": "1 Corinti 6:18" },
    { "id": 220, "parola": "FRATELLO", "def": "Membro della stessa famiglia o della congregazione.", "rif": "Matteo 23:8" },
    { "id": 221, "parola": "FRIGIA", "def": "Regione interna dell'Asia Minore.", "rif": "Atti 16:6" },
    { "id": 222, "parola": "FRUTTO", "def": "Prodotto di una pianta o risultato di un'azione.", "rif": "Galati 5:22" },
    { "id": 223, "parola": "GABAON", "def": "Citta i cui abitanti ingannarono Giosue.", "rif": "Giosue 9:3" },
    { "id": 224, "parola": "GABRIELE", "def": "Angelo messaggero inviato da Dio a Daniele e Maria.", "rif": "Luca 1:26" },
    { "id": 225, "parola": "GALAAD", "def": "Regione montuosa nota per il suo balsamo.", "rif": "Geremia 8:22" },
    { "id": 226, "parola": "GALAZIA", "def": "Regione dell'Asia Minore sede di molte congregazioni.", "rif": "Galati 1:2" },
    { "id": 227, "parola": "GALILEA", "def": "Regione settentrionale della Palestina.", "rif": "Matteo 4:12" },
    { "id": 228, "parola": "GAT", "def": "Citta d'origine del gigante Golia.", "rif": "1 Samuele 17:4" },
    { "id": 229, "parola": "GAZA", "def": "Citta filistea dove Sansone fu imprigionato.", "rif": "Giudici 16:21" },
    { "id": 230, "parola": "GEENA", "def": "Simbolo di distruzione eterna, dalla valle di Innom.", "rif": "Matteo 5:22" },
    { "id": 231, "parola": "GENEALOGIA", "def": "Elenco degli antenati di una persona o famiglia.", "rif": "Matteo 1:1" },
    { "id": 232, "parola": "GENTILE", "def": "Persona di nazione non ebraica.", "rif": "Romani 1:16" },
    { "id": 233, "parola": "GERICO", "def": "Citta dalle mura abbattute miracolosamente.", "rif": "Giosue 6:1" },
    { "id": 234, "parola": "GERUSALEMME", "def": "Citta santa e sede del tempio di Geova.", "rif": "2 Samuele 5:5" },
    { "id": 235, "parola": "GESU", "def": "Nome del Figlio di Dio, il Messia promesso.", "rif": "Matteo 1:21" },
    { "id": 236, "parola": "GETSEMANI", "def": "Giardino ai piedi del Monte degli Ulivi.", "rif": "Matteo 26:36" },
    { "id": 237, "parola": "GHERIZIM", "def": "Monte su cui furono pronunciate le benedizioni.", "rif": "Deuteronomio 11:29" },
    { "id": 238, "parola": "GIAGGIOLO", "def": "Pianta erbacea citata in contesti poetici biblici.", "rif": "Glossario" },
    { "id": 239, "parola": "GIACOMO", "def": "Nome di due apostoli e di un fratellastro di Gesu.", "rif": "Matteo 4:21" },
    { "id": 240, "parola": "GIARDINODIEDEN", "def": "Dimora originale dell'uomo creata da Dio.", "rif": "Genesi 2:8" },
    { "id": 241, "parola": "GIOPPE", "def": "Citta portuale dove Pietro risuscito Tabita.", "rif": "Atti 9:36" },
    { "id": 242, "parola": "GIORDANO", "def": "Fiume principale della Terra Promessa.", "rif": "Giosue 3:1" },
    { "id": 243, "parola": "GIUBILEO", "def": "Anno di liberazione ogni 50 anni in Israele.", "rif": "Levitico 25:10" },
    { "id": 244, "parola": "GIUDA", "def": "Quarto figlio di Giacobbe o nome di una tribu e regno.", "rif": "Genesi 29:35" },
    { "id": 245, "parola": "GIUDAISMO", "def": "Insieme delle credenze e delle pratiche religiose degli ebrei.", "rif": "Galati 1:13" },
    { "id": 246, "parola": "GIUDEA", "def": "Regione meridionale dove si trova Gerusalemme.", "rif": "Matteo 2:1" },
    { "id": 247, "parola": "GIUDICE", "def": "Persona incaricata da Dio di liberare e guidare il suo popolo.", "rif": "Giudici 2:16" },
    { "id": 248, "parola": "GIUDIZIO", "def": "Decisione o verdetto emesso da un'autorita o da Dio.", "rif": "Giovanni 5:22" },
    { "id": 249, "parola": "GIURAMENTO", "def": "Dichiarazione solenne per confermare la verita di qualcosa.", "rif": "Ebrei 6:16" },
    { "id": 250, "parola": "GIURURA", "def": "Regione collinare o deserta citata nei profeti.", "rif": "Glossario" },
    { "id": 251, "parola": "GIUSTIZIA", "def": "Qualita di cio che e retto secondo le norme divine.", "rif": "Matteo 6:33" },
    { "id": 252, "parola": "GIUSTO", "def": "Persona che agisce in conformita alla volonta di Dio.", "rif": "Romani 1:17" },
    { "id": 253, "parola": "GLORIA", "def": "Splendore, onore o maesta che emana da Dio.", "rif": "Rivelazione 4:11" },
    { "id": 254, "parola": "GLOSSOLALIA", "def": "Dono miracoloso di parlare in lingue diverse.", "rif": "1 Corinti 12:10" },
    { "id": 255, "parola": "GOG", "def": "Nome simbolico del nemico che attacca il popolo di Dio.", "rif": "Ezechiele 38:2" },
    { "id": 256, "parola": "GOLGOTA", "def": "Luogo del teschio, dove Gesu fu messo al palo.", "rif": "Matteo 27:33" },
    { "id": 257, "parola": "GOMORRA", "def": "Citta distrutta da Dio insieme a Sodoma.", "rif": "Genesi 19:24" },
    { "id": 258, "parola": "GRAZIA", "def": "Favore o benignita immeritata concessa da Dio.", "rif": "Efesini 2:8" },
    { "id": 259, "parola": "GRECIA", "def": "Nazione che divenne la quinta potenza mondiale biblica.", "rif": "Daniele 8:21" },
    { "id": 260, "parola": "GRECO", "def": "Lingua in cui furono scritti i Vangeli e le Lettere.", "rif": "Giovanni 19:20" },
    { "id": 261, "parola": "IAMBRE", "def": "Mago egiziano che resistette a Mose insieme a Ianne.", "rif": "2 Timoteo 3:8" },
    { "id": 262, "parola": "IANNE", "def": "Uno dei maghi d'Egitto che si oppose a Mose.", "rif": "2 Timoteo 3:8" },
    { "id": 263, "parola": "IABBOC", "def": "Affluente del Giordano dove Giacobbe lotto con l'angelo.", "rif": "Genesi 32:22" },
    { "id": 264, "parola": "IDOLO", "def": "Immagine o oggetto usato come divinita nel culto.", "rif": "1 Giovanni 5:21" },
    { "id": 265, "parola": "IGNORANZA", "def": "Mancanza di conoscenza della verita di Dio.", "rif": "Atti 17:30" },
    { "id": 266, "parola": "ILLIRICO", "def": "Regione a nord della Macedonia raggiunta da Paolo.", "rif": "Romani 15:19" },
    { "id": 267, "parola": "IMMORTALITA", "def": "Qualita di una vita che non puo morire o corrompersi.", "rif": "1 Corinti 15:53" },
    { "id": 268, "parola": "IMPOSIZIONEDELLEMANI", "def": "Gesto per designare qualcuno per un compito speciale.", "rif": "Atti 6:6" },
    { "id": 269, "parola": "INCENSO", "def": "Sostanza aromatica bruciata nel servizio del tempio.", "rif": "Esodo 30:1" },
    { "id": 270, "parola": "INCREDULITA", "def": "Mancanza di fede o rifiuto di credere a Dio.", "rif": "Ebrei 3:19" },
    { "id": 271, "parola": "INFEDELTA", "def": "Mancanza di lealta o violazione di un patto.", "rif": "Matteo 19:9" },
    { "id": 272, "parola": "INFERNO", "def": "Traduzione errata di termini che indicano la tomba.", "rif": "Glossario" },
    { "id": 273, "parola": "INIQUITA", "def": "Mancanza di legge o comportamento malvagio.", "rif": "Matteo 24:12" },
    { "id": 274, "parola": "INNO", "def": "Canto di lode o ringraziamento rivolto a Dio.", "rif": "Colossesi 3:16" },
    { "id": 275, "parola": "INSEGNAMENTO", "def": "Istruzione impartita per trasmettere la verita.", "rif": "Matteo 7:28" },
    { "id": 276, "parola": "ISPIRAZIONE", "def": "Influenza divina sugli scrittori della Bibbia.", "rif": "2 Timoteo 3:16" },
    { "id": 277, "parola": "ISRAELE", "def": "Nome dato a Giacobbe e poi alla nazione eletta.", "rif": "Genesi 32:28" },
    { "id": 278, "parola": "ITALIA", "def": "Paese da cui provenivano Aquila e Priscilla.", "rif": "Atti 18:2" },
    { "id": 279, "parola": "ITUREA", "def": "Piccola regione a nord-est del Mar di Galilea.", "rif": "Luca 3:1" },
    { "id": 280, "parola": "LAODICEA", "def": "Citta rimproverata per la sua tiepidezza spirituale.", "rif": "Rivelazione 3:14" },
    { "id": 281, "parola": "LAVORO", "def": "Attivita svolta per servire Dio o provvedere a se.", "rif": "2 Tessalonicesi 3:10" },
    { "id": 282, "parola": "LEA", "def": "Moglie di Giacobbe e madre di sei delle dodici tribu.", "rif": "Genesi 29:23" },
    { "id": 283, "parola": "LEBBRA", "def": "Malattia che rendeva cerimonialmente impuri.", "rif": "Levitico 13:2" },
    { "id": 284, "parola": "LEGGE", "def": "Insieme di norme date da Dio tramite Mose.", "rif": "Esodo 24:12" },
    { "id": 285, "parola": "LEGIONE", "def": "Unita dell'esercito romano composta da migliaia di soldati.", "rif": "Matteo 26:53" },
    { "id": 286, "parola": "LEVITA", "def": "Discendente di Levi addetto al servizio del tempio.", "rif": "Numeri 3:6" },
    { "id": 287, "parola": "LIBANO", "def": "Catena montuosa nota per i suoi maestosi cedri.", "rif": "1 Re 5:6" },
    { "id": 288, "parola": "LIBERTA", "def": "Condizione di chi e svincolato dal peccato e dalla morte.", "rif": "Giovanni 8:32" },
    { "id": 289, "parola": "LIBIA", "def": "Regione dell'Africa settentrionale.", "rif": "Atti 2:10" },
    { "id": 290, "parola": "LIBRO", "def": "Rotolo o codice contenente scritti sacri.", "rif": "Rivelazione 20:12" },
    { "id": 291, "parola": "LICAONIA", "def": "Regione dell'Asia Minore dove Paolo predico.", "rif": "Atti 14:6" },
    { "id": 292, "parola": "LICIA", "def": "Provincia sulla costa meridionale dell'Asia Minore.", "rif": "Atti 27:5" },
    { "id": 293, "parola": "LIDIA", "def": "Regione dell'Asia Minore occidentale.", "rif": "Glossario" },
    { "id": 294, "parola": "LINGUA", "def": "Facolta di parlare o idioma di un popolo.", "rif": "1 Corinti 14:2" },
    { "id": 295, "parola": "LINO", "def": "Fibra usata per le vesti dei sacerdoti.", "rif": "Esodo 28:39" },
    { "id": 296, "parola": "LISTRA", "def": "Citta della Licaonia dove Paolo fu lapidato.", "rif": "Atti 14:8" },
    { "id": 297, "parola": "LITURGIA", "def": "Servizio pubblico o ufficio sacro svolto per Dio.", "rif": "Glossario" },
    { "id": 298, "parola": "LOGO", "def": "Termine greco per parola o ragione; riferito a Gesu.", "rif": "Giovanni 1:1" },
    { "id": 299, "parola": "LUCA", "def": "Medico e scrittore di un Vangelo e degli Atti.", "rif": "Colossesi 4:14" },
    { "id": 300, "parola": "LUCE", "def": "Simbolo di verita, santita e guida divina.", "rif": "Salmo 119:105" },
    { "id": 301, "parola": "LUCIFERO", "def": "Significa portatore di luce; usato in senso figurato.", "rif": "Isaia 14:12" },
    { "id": 302, "parola": "LUNA", "def": "Corpo celeste usato per segnare i mesi e le feste.", "rif": "Salmo 104:19" },
    { "id": 303, "parola": "MACEDONIA", "def": "Regione della Grecia dove Paolo ando dopo una visione.", "rif": "Atti 16:9" },
    { "id": 304, "parola": "MADIAN", "def": "Regione abitata dai discendenti di Abraamo e Chetura.", "rif": "Esodo 2:15" },
    { "id": 305, "parola": "MAESTRO", "def": "Persona che insegna con autorita la Parola di Dio.", "rif": "Matteo 23:8" },
    { "id": 306, "parola": "MAGIA", "def": "Ricorso a poteri occulti o demonici.", "rif": "Atti 19:19" },
    { "id": 307, "parola": "MALATTIA", "def": "Condizione di imperfezione fisica o spirituale.", "rif": "Matteo 9:35" },
    { "id": 308, "parola": "MALEDIZIONE", "def": "Invocazione del male o sentenza divina avversa.", "rif": "Genesi 3:14" },
    { "id": 309, "parola": "MALIZIA", "def": "Cattiveria d'animo o intenzione di nuocere.", "rif": "1 Corinti 14:20" },
    { "id": 310, "parola": "MALTA", "def": "Isola dove Paolo fece naufragio.", "rif": "Atti 28:1" },
    { "id": 311, "parola": "MAMMONA", "def": "Termine caldeo per indicare ricchezza o denaro.", "rif": "Matteo 6:24" },
    { "id": 312, "parola": "MANAEN", "def": "Membro della congregazione di Antiochia.", "rif": "Atti 13:1" },
    { "id": 313, "parola": "MANDRAGORA", "def": "Pianta le cui radici erano associate alla fertilita.", "rif": "Genesi 30:14" },
    { "id": 314, "parola": "MANNA", "def": "Cibo miracoloso fornito da Dio nel deserto.", "rif": "Esodo 16:31" },
    { "id": 315, "parola": "MANOSCRITTO", "def": "Documento scritto a mano su papiro o pergamena.", "rif": "Glossario" },
    { "id": 316, "parola": "MARCO", "def": "Evangelista e collaboratore di Paolo e Pietro.", "rif": "Colossesi 4:10" },
    { "id": 317, "parola": "MARIA", "def": "Nome della madre di Gesu e di altre donne fedeli.", "rif": "Luca 1:27" },
    { "id": 318, "parola": "MARTIRE", "def": "Chi rende testimonianza fino alla morte.", "rif": "Atti 22:20" },
    { "id": 319, "parola": "MATTEO", "def": "Apostolo ed evangelista, ex esattore di tasse.", "rif": "Matteo 9:9" },
    { "id": 320, "parola": "MEDIA", "def": "Regione abitata dai discendenti di Madai.", "rif": "Daniele 5:28" },
    { "id": 321, "parola": "MEDIATORE", "def": "Chi interviene tra Dio e gli uomini.", "rif": "1 Timoteo 2:5" },
    { "id": 322, "parola": "MEDICINA", "def": "Sostanza o cura per la guarigione fisica.", "rif": "Proverbi 17:22" },
    { "id": 323, "parola": "MELCHISEDEC", "def": "Re di Salem e sacerdote dell'Iddio Altissimo.", "rif": "Genesi 14:18" },
    { "id": 324, "parola": "MEMORIA", "def": "Facolta di ricordare o commemorazione sacra.", "rif": "Luca 22:19" },
    { "id": 325, "parola": "MENZOGNA", "def": "Affermazione falsa contraria alla verita di Dio.", "rif": "Giovanni 8:44" },
    { "id": 326, "parola": "MESOPOTAMIA", "def": "Terra tra i due fiumi Eufrate e Tigri.", "rif": "Genesi 24:10" },
    { "id": 327, "parola": "MESSIA", "def": "Dall'ebraico Unto; il liberatore promesso.", "rif": "Giovanni 1:41" },
    { "id": 328, "parola": "METRO", "def": "Unita di misura o ritmo poetico dei Salmi.", "rif": "Glossario" },
    { "id": 329, "parola": "MICHELE", "def": "Nome dell'arcangelo, capo degli eserciti celesti.", "rif": "Daniele 12:1" },
    { "id": 330, "parola": "MIGLIO", "def": "Misura di distanza usata dai romani.", "rif": "Matteo 5:41" },
    { "id": 331, "parola": "MILIZIA", "def": "Esercito o servizio militare, anche spirituale.", "rif": "2 Corinti 10:4" },
    { "id": 332, "parola": "MILLENNIO", "def": "Periodo di mille anni del regno di Cristo.", "rif": "Rivelazione 20:4" },
    { "id": 333, "parola": "MINISTERO", "def": "Servizio sacro svolto per Dio e per il prossimo.", "rif": "2 Timoteo 4:5" },
    { "id": 334, "parola": "MIRACOLO", "def": "Atto potente che supera le leggi naturali conosciute.", "rif": "Atti 2:22" },
    { "id": 335, "parola": "MISERICORDIA", "def": "Compassione attiva che spinge al perdono.", "rif": "Matteo 5:7" },
    { "id": 336, "parola": "MISSIONARIO", "def": "Chi e inviato a predicare in territori stranieri.", "rif": "Atti 13:2" },
    { "id": 337, "parola": "MISTERO", "def": "Verita sacra precedentemente nascosta e poi rivelata.", "rif": "Efesini 3:4" },
    { "id": 338, "parola": "MITRA", "def": "Copricapo cerimoniale del sommo sacerdote.", "rif": "Esodo 28:4" },
    { "id": 339, "parola": "MOAB", "def": "Altopiano a est del Mar Morto.", "rif": "Genesi 19:37" },
    { "id": 340, "parola": "MORTE", "def": "Cessazione della vita; nemico dell'umanita.", "rif": "1 Corinti 15:26" },
    { "id": 341, "parola": "MOSE", "def": "Condottiero e legislatore d'Israele.", "rif": "Esodo 3:10" },
    { "id": 342, "parola": "MUSICA", "def": "Arte del suono usata per lodare Geova.", "rif": "Salmo 150:3" },
    { "id": 343, "parola": "NABUCODONOSOR", "def": "Re babilonese che distrusse Gerusalemme.", "rif": "2 Re 25:1" },
    { "id": 344, "parola": "NAZARENO", "def": "Abitante di Nazaret; titolo riferito a Gesu.", "rif": "Matteo 2:23" },
    { "id": 345, "parola": "NAZARET", "def": "Citta della Galilea dove crebbe Gesu.", "rif": "Matteo 2:23" },
    { "id": 346, "parola": "NAZIREATO", "def": "Condizione di chi faceva voto di nazireo.", "rif": "Numeri 6:2" },
    { "id": 347, "parola": "NEBO", "def": "Monte da cui Mose vide la Terra Promessa.", "rif": "Deuteronomio 34:1" },
    { "id": 348, "parola": "NECROPOLI", "def": "Vasta zona adibita a sepoltura.", "rif": "Glossario" },
    { "id": 349, "parola": "NEMICO", "def": "Chi si oppone a Dio o al suo popolo.", "rif": "Matteo 13:39" },
    { "id": 350, "parola": "NERO", "def": "Imperatore romano sotto cui inizio la persecuzione.", "rif": "Glossario" },
    { "id": 351, "parola": "NILO", "def": "Fiume principale dell'Egitto.", "rif": "Esodo 7:17" },
    { "id": 352, "parola": "NIMRUD", "def": "Citta assira fondata da Nimrod.", "rif": "Genesi 10:11" },
    { "id": 353, "parola": "NINIVE", "def": "Capitale dell'Assiria a cui predico Giona.", "rif": "Giona 1:2" },
    { "id": 354, "parola": "NOE", "def": "Costruttore dell'arca e sopravvissuto al Diluvio.", "rif": "Genesi 6:8" },
    { "id": 355, "parola": "NOME", "def": "Designazione che identifica la persona o Dio.", "rif": "Esodo 3:15" },
    { "id": 356, "parola": "NORMA", "def": "Regola di condotta stabilita da Dio.", "rif": "Salmo 119:105" },
    { "id": 357, "parola": "NOTIZIA", "def": "Messaggio o annuncio, spesso di salvezza.", "rif": "Isaia 52:7" },
    { "id": 358, "parola": "NOZZE", "def": "Celebrazione del patto matrimoniale.", "rif": "Matteo 25:1" },
    { "id": 359, "parola": "NUMERI", "def": "Quarto libro del Pentateuco o cifre simboliche.", "rif": "Glossario" },
    { "id": 360, "parola": "OBBEDIENZA", "def": "Sottomissione alla volonta e alle leggi di Dio.", "rif": "1 Samuele 15:22" },
    { "id": 361, "parola": "OBLAZIONE", "def": "Offerta o dono presentato a Dio.", "rif": "Levitico 2:1" },
    { "id": 362, "parola": "OCCULTO", "def": "Pratiche legate allo spiritismo e ai demoni.", "rif": "Deuteronomio 18:10" },
    { "id": 363, "parola": "ODIO", "def": "Forte avversione o disprezzo, spesso ingiustificato.", "rif": "1 Giovanni 3:15" },
    { "id": 364, "parola": "OFFERTA", "def": "Sacrificio o dono presentato sull'altare.", "rif": "Genesi 4:4" },
    { "id": 365, "parola": "OLIO", "def": "Sostanza usata per l'unzione e l'illuminazione.", "rif": "Salmo 23:5" },
    { "id": 366, "parola": "OLIVETO", "def": "Monte a est di Gerusalemme amato da Gesu.", "rif": "Matteo 21:1" },
    { "id": 367, "parola": "OLOCAUSTO", "def": "Sacrificio animale interamente bruciato per Dio.", "rif": "Levitico 1:3" },
    { "id": 368, "parola": "OMBRA", "def": "Rappresentazione simbolica di realta future.", "rif": "Ebrei 10:1" },
    { "id": 369, "parola": "ONESTA", "def": "Qualita di chi agisce con sincerita e rettitudine.", "rif": "Ebrei 13:18" },
    { "id": 370, "parola": "ONORE", "def": "Rispetto e stima dovuti a Dio e alle autorita.", "rif": "Rivelazione 4:11" },
    { "id": 371, "parola": "OPERA", "def": "Azione compiuta per fede o frutto del lavoro.", "rif": "Giacomo 2:17" },
    { "id": 372, "parola": "ORACOLO", "def": "Messaggio profetico o risposta divina.", "rif": "Atti 7:38" },
    { "id": 373, "parola": "OREB", "def": "Altro nome del monte Sinai, monte del vero Dio.", "rif": "Esodo 3:1" },
    { "id": 374, "parola": "ORFANO", "def": "Bambino privo di genitori, oggetto di cura divina.", "rif": "Salmo 68:5" },
    { "id": 375, "parola": "ORGOGLIO", "def": "Sentimento di superiorita condannato da Dio.", "rif": "Proverbi 16:18" },
    { "id": 376, "parola": "ORO", "def": "Metallo prezioso usato nel tabernacolo e nel tempio.", "rif": "Esodo 25:11" },
    { "id": 377, "parola": "OSCURITA", "def": "Assenza di luce, simbolo di ignoranza o male.", "rif": "Isaia 60:2" },
    { "id": 378, "parola": "OSSEQUIO", "def": "Atto di sottomissione o omaggio reverente.", "rif": "Glossario" },
    { "id": 379, "parola": "OVILE", "def": "Recinto protetto per le pecore.", "rif": "Giovanni 10:1" },
    { "id": 380, "parola": "PAGANESIMO", "def": "Insieme di riti e credenze di chi non adora il vero Dio.", "rif": "Glossario" },
    { "id": 381, "parola": "PALO", "def": "Vedi Strumento di tortura; legno usato per le esecuzioni.", "rif": "Matteo 27:32" },
    { "id": 382, "parola": "PAMPILIA", "def": "Provincia costiera dell'Asia Minore.", "rif": "Atti 13:13" },
    { "id": 383, "parola": "PANE", "def": "Alimento base, spesso usato come simbolo di sostentamento.", "rif": "Matteo 6:11" },
    { "id": 384, "parola": "PANTANO", "def": "Zona paludosa o regione specifica citata simbolicamente.", "rif": "Ezechiele 47:11" },
    { "id": 385, "parola": "PAPIRO", "def": "Materiale scrittorio ricavato da una pianta acquatica.", "rif": "2 Giovanni 12" },
    { "id": 386, "parola": "PARABOLA", "def": "Breve racconto simbolico per insegnare una verita.", "rif": "Matteo 13:3" },
    { "id": 387, "parola": "PARADISO", "def": "Giardino o parco; futuro stato della terra.", "rif": "Luca 23:43" },
    { "id": 388, "parola": "PAROLADIDIO", "def": "Messaggio di Geova contenuto nelle Sacre Scritture.", "rif": "Ebrei 4:12" },
    { "id": 389, "parola": "PASQUA", "def": "Festa che ricorda la liberazione dall'Egitto.", "rif": "Esodo 12:11" },
    { "id": 390, "parola": "PASTORE", "def": "Chi cura il gregge; titolo per chi guida la congregazione.", "rif": "Efesini 4:11" },
    { "id": 391, "parola": "PATTO", "def": "Accordo o contratto solenne tra due parti.", "rif": "Genesi 9:9" },
    { "id": 392, "parola": "PECCATO", "def": "Mancare il bersaglio della perfezione di Dio.", "rif": "Romani 3:23" },
    { "id": 393, "parola": "PENTECOSTE", "def": "Festa del raccolto 50 giorni dopo la Pasqua.", "rif": "Atti 2:1" },
    { "id": 394, "parola": "PERDONO", "def": "Atto di cancellare una colpa o un debito.", "rif": "Colossesi 3:13" },
    { "id": 395, "parola": "PEREA", "def": "Regione oltre il Giordano visitata da Gesu.", "rif": "Glossario" },
    { "id": 396, "parola": "PERGAMENA", "def": "Pelle di animale trattata per la scrittura.", "rif": "2 Timoteo 4:13" },
    { "id": 397, "parola": "PERGAMO", "def": "Citta dell'Asia dove si trovava il trono di Satana.", "rif": "Rivelazione 2:12" },
    { "id": 398, "parola": "PERSECUZIONE", "def": "Oppressione o maltrattamento a motivo della fede.", "rif": "Matteo 5:10" },
    { "id": 399, "parola": "PERSIA", "def": "Potenza mondiale che succedette a Babilonia.", "rif": "Daniele 5:28" },
    { "id": 400, "parola": "PIETRAANGOLARE", "def": "Pietra fondamentale posta all'angolo di un edificio.", "rif": "Efesini 2:20" },
    { "id": 401, "parola": "PONTO", "def": "Regione costiera del Mar Nero.", "rif": "1 Pietro 1:1" },
    { "id": 402, "parola": "PONZIOPILATO", "def": "Governatore romano che condanno Gesu.", "rif": "Luca 3:1" },
    { "id": 403, "parola": "PORPORA", "def": "Colore e tessuto pregiato simbolo di regalita.", "rif": "Marco 15:17" },
    { "id": 404, "parola": "POTENZA", "def": "Forza o autorita esercitata da Dio o da governi.", "rif": "Rivelazione 19:1" },
    { "id": 405, "parola": "PREGHIERA", "def": "Comunicazione rivolta a Dio con fede.", "rif": "Filippesi 4:6" },
    { "id": 406, "parola": "PREMORIENZA", "def": "Morte avvenuta prima di un evento o di un'altra persona.", "rif": "Glossario" },
    { "id": 407, "parola": "PRESBITERO", "def": "Termine greco per anziano.", "rif": "Tito 1:5" },
    { "id": 408, "parola": "PROFETA", "def": "Chi trasmette messaggi da parte di Dio.", "rif": "Amos 3:7" },
    { "id": 409, "parola": "PROMESSE", "def": "Assicurazioni date da Dio riguardo al futuro.", "rif": "2 Corinti 1:20" },
    { "id": 410, "parola": "PROSELITO", "def": "Convertito che abbracciava il giudaismo.", "rif": "Matteo 23:15" },
    { "id": 411, "parola": "PURIFICAZIONE", "def": "Rito per rimuovere l'impurita cerimoniale.", "rif": "Levitico 12:4" },
    { "id": 412, "parola": "RACCOLTO", "def": "Raccolta dei frutti della terra o di nuovi discepoli.", "rif": "Matteo 9:37" },
    { "id": 413, "parola": "RE", "def": "Sovrano che esercita l'autorita su un popolo.", "rif": "1 Samuele 8:5" },
    { "id": 414, "parola": "REAZIONE", "def": "Risposta a un insegnamento o a un'azione.", "rif": "Glossario" },
    { "id": 415, "parola": "REDENZIONE", "def": "Liberazione ottenuta tramite un prezzo.", "rif": "Efesini 1:7" },
    { "id": 416, "parola": "REGNODIDIO", "def": "Governo celeste con a capo Gesu Cristo.", "rif": "Matteo 6:10" },
    { "id": 417, "parola": "REIETTO", "def": "Persona allontanata o disapprovata da Dio.", "rif": "1 Corinti 9:27" },
    { "id": 418, "parola": "RESTO", "def": "Piccolo gruppo di persone che rimane fedele.", "rif": "Romani 11:5" },
    { "id": 419, "parola": "RISCATTO", "def": "Prezzo pagato per liberare dal peccato.", "rif": "Matteo 20:28" },
    { "id": 420, "parola": "RISURREZIONE", "def": "Ritorno in vita di chi e morto.", "rif": "Giovanni 5:28" },
    { "id": 421, "parola": "RIVELAZIONE", "def": "Manifestazione di verita nascoste da parte di Dio.", "rif": "Rivelazione 1:1" },
    { "id": 422, "parola": "ROMA", "def": "Capitale dell'impero e sesta potenza mondiale.", "rif": "Atti 18:2" },
    { "id": 423, "parola": "ROTOLO", "def": "Striscia di pergamena o papiro avvolta su un bastone.", "rif": "Luca 4:17" },
    { "id": 424, "parola": "SABATO", "def": "Giorno di riposo prescritto dalla Legge.", "rif": "Esodo 20:8" },
    { "id": 425, "parola": "SACERDOTE", "def": "Chi rappresenta gli uomini davanti a Dio.", "rif": "Ebrei 5:1" },
    { "id": 426, "parola": "SACRIFICIO", "def": "Offerta presentata a Dio per espiazione o lode.", "rif": "Ebrei 13:15" },
    { "id": 427, "parola": "SADDUCEI", "def": "Setta giudaica che non credeva nella risurrezione.", "rif": "Matteo 22:23" },
    { "id": 428, "parola": "SALDO", "def": "Stabile e incrollabile nella fede.", "rif": "1 Corinti 15:58" },
    { "id": 429, "parola": "SALE", "def": "Sostanza usata per conservare e dare sapore.", "rif": "Matteo 5:13" },
    { "id": 430, "parola": "SALVEZZA", "def": "Liberazione dal peccato e dalla morte.", "rif": "Atti 4:12" },
    { "id": 431, "parola": "SAMARIA", "def": "Capitale del regno delle dieci tribu d'Israele.", "rif": "1 Re 16:24" },
    { "id": 432, "parola": "SAMARITANO", "def": "Abitante della Samaria, spesso disprezzato dai giudei.", "rif": "Luca 10:33" },
    { "id": 433, "parola": "SANTITA", "def": "Condizione di assoluta purezza e separazione dal male.", "rif": "1 Pietro 1:16" },
    { "id": 434, "parola": "SANTUARIO", "def": "Luogo dedicato al culto e alla presenza di Dio.", "rif": "Esodo 25:8" },
    { "id": 435, "parola": "SARDI", "def": "Citta dell'Asia Minore sede di una delle sette congregazioni.", "rif": "Rivelazione 3:1" },
    { "id": 436, "parola": "SATANA", "def": "Oppositore e nemico principale di Geova.", "rif": "Giobbe 1:6" },
    { "id": 437, "parola": "SCEOL", "def": "Termine ebraico per la tomba comune del genere umano.", "rif": "Ecclesiaste 9:10" },
    { "id": 438, "parola": "SCRIBA", "def": "Copiaista ed esperto della Legge.", "rif": "Esdra 7:6" },
    { "id": 439, "parola": "SCRITTURE", "def": "Insieme dei libri ispirati da Dio.", "rif": "2 Timoteo 3:16" },
    { "id": 440, "parola": "SEME", "def": "Discendenza o prole; riferito anche al Messia.", "rif": "Genesi 3:15" },
    { "id": 441, "parola": "SETTA", "def": "Gruppo con dottrine che si separano dalla verita.", "rif": "Atti 24:5" },
    { "id": 442, "parola": "SICHEM", "def": "Citta tra il monte Ebal e il monte Gherizim.", "rif": "Genesi 12:6" },
    { "id": 443, "parola": "SIDONE", "def": "Antica citta fenicia a nord di Tiro.", "rif": "Genesi 10:15" },
    { "id": 444, "parola": "SIGILLO", "def": "Marchio di proprieta o autenticita.", "rif": "Efesini 1:13" },
    { "id": 445, "parola": "SILO", "def": "Luogo dove rimase il tabernacolo per lungo tempo.", "rif": "Giosue 18:1" },
    { "id": 446, "parola": "SINAGOGA", "def": "Luogo di assemblea per l'istruzione giudaica.", "rif": "Luca 4:16" },
    { "id": 447, "parola": "SINAI", "def": "Monte dove Mose ricevette la Legge.", "rif": "Esodo 19:2" },
    { "id": 448, "parola": "SINEDRIO", "def": "Alta corte giudaica di Gerusalemme.", "rif": "Atti 5:27" },
    { "id": 449, "parola": "SION", "def": "Nome della collina di Gerusalemme e della citta stessa.", "rif": "Salmo 2:6" },
    { "id": 450, "parola": "SIRIA", "def": "Regione a nord della Terra Promessa.", "rif": "Matteo 4:24" },
    { "id": 451, "parola": "SISTEMADICOSE", "def": "Ordine mondiale o epoca storica.", "rif": "Galati 1:4" },
    { "id": 452, "parola": "SMIRNE", "def": "Citta costiera dell'Asia Minore citata in Rivelazione.", "rif": "Rivelazione 2:8" },
    { "id": 453, "parola": "SODOMA", "def": "Citta della pianura distrutta dal fuoco.", "rif": "Genesi 19:24" },
    { "id": 454, "parola": "SOMMOSACERDOTE", "def": "Capo dei sacerdoti e unico a entrare nel Santissimo.", "rif": "Ebrei 4:14" },
    { "id": 455, "parola": "SORVEGLIANTE", "def": "Chi ha la responsabilita di guidare la congregazione.", "rif": "Atti 20:28" },
    { "id": 456, "parola": "SPAGNA", "def": "Nazione che Paolo desiderava visitare.", "rif": "Romani 15:24" },
    { "id": 457, "parola": "SPIRITOSANTO", "def": "Forza attiva impiegata da Dio.", "rif": "Genesi 1:2" },
    { "id": 458, "parola": "SUSA", "def": "Capitale dell'impero persiano ai tempi di Ester.", "rif": "Ester 2:8" },
    { "id": 459, "parola": "TABERNACOLO", "def": "Tenda trasportabile usata per l'adorazione d'Israele.", "rif": "Esodo 25:9" },
    { "id": 460, "parola": "TABOR", "def": "Monte della Galilea dove Barac raduno l'esercito.", "rif": "Giudici 4:6" },
    { "id": 461, "parola": "TALENTO", "def": "Unita di peso e moneta di maggior valore.", "rif": "Matteo 25:15" },
    { "id": 462, "parola": "TARSO", "def": "Citta natale dell'apostolo Paolo in Cilicia.", "rif": "Atti 9:11" },
    { "id": 463, "parola": "TARTARO", "def": "Condizione di umiliazione per gli angeli ribelli.", "rif": "2 Pietro 2:4" },
    { "id": 464, "parola": "TEMPIO", "def": "Edificio permanente che sostitui il tabernacolo.", "rif": "1 Re 6:1" },
    { "id": 465, "parola": "TENTAZIONE", "def": "Prova o sollecitazione a compiere il male.", "rif": "Matteo 6:13" },
    { "id": 466, "parola": "TERREMOTI", "def": "Scosse della terra predette come segno della fine.", "rif": "Matteo 24:7" },
    { "id": 467, "parola": "TESSALONICA", "def": "Citta portuale della Macedonia a cui Paolo scrisse.", "rif": "Atti 17:1" },
    { "id": 468, "parola": "TESTIMONIANZA", "def": "Dichiarazione o prova di fatti riguardanti Dio.", "rif": "Atti 1:8" },
    { "id": 469, "parola": "TETRAGRAMMA", "def": "Le quattro lettere ebraiche del nome divino (YHWH).", "rif": "Esodo 3:15" },
    { "id": 470, "parola": "TETRARCA", "def": "Governatore di una quarta parte di una provincia.", "rif": "Luca 3:1" },
    { "id": 471, "parola": "TIATIRA", "def": "Citta nota per la vendita della porpora.", "rif": "Atti 16:14" },
    { "id": 472, "parola": "TIGRI", "def": "Fiume dell'Assiria, uno dei quattro dell'Eden.", "rif": "Genesi 2:14" },
    { "id": 473, "parola": "TIMOREDIDIO", "def": "Sano timore e profondo rispetto verso il Creatore.", "rif": "Salmo 111:10" },
    { "id": 474, "parola": "TIRANNIA", "def": "Esercizio oppressivo e ingiusto del potere.", "rif": "Glossario" },
    { "id": 475, "parola": "TIRO", "def": "Importante citta portuale della Fenicia.", "rif": "Isaia 23:1" },
    { "id": 476, "parola": "TRADIZIONE", "def": "Insieme di usanze tramandate, a volte contrarie alla Legge.", "rif": "Matteo 15:3" },
    { "id": 477, "parola": "TRASFIGURAZIONE", "def": "Visione in cui Gesu apparve in gloria davanti a tre apostoli.", "rif": "Matteo 17:2" },
    { "id": 478, "parola": "TRIBOLAZIONE", "def": "Periodo di grave sofferenza o angoscia.", "rif": "Matteo 24:21" },
    { "id": 479, "parola": "TRIBU", "def": "Ciascuna delle dodici divisioni del popolo d'Israele.", "rif": "Genesi 49:28" },
    { "id": 480, "parola": "TRINITA", "def": "Dottrina non biblica sulla natura di Dio.", "rif": "Glossario" },
    { "id": 481, "parola": "TRONO", "def": "Seggio regale, simbolo di autorita e governo.", "rif": "Rivelazione 4:2" },
    { "id": 482, "parola": "UMILTA", "def": "Modestia e assenza di orgoglio davanti a Dio.", "rif": "Giacomo 4:6" },
    { "id": 483, "parola": "UNTO", "def": "Scelto e incaricato tramite l'unzione spirituale.", "rif": "2 Corinti 1:21" },
    { "id": 484, "parola": "UNZIONE", "def": "Versamento di olio o spirito per un incarico sacro.", "rif": "Esodo 28:41" },
    { "id": 485, "parola": "UR", "def": "Citta dei caldei da cui parti Abraamo.", "rif": "Genesi 11:31" },
    { "id": 486, "parola": "URIMETUMMIM", "def": "Oggetti usati dal sommo sacerdote per consultare Dio.", "rif": "Esodo 28:30" },
    { "id": 487, "parola": "USURA", "def": "Prestito di denaro a interessi esorbitanti.", "rif": "Esodo 22:25" },
    { "id": 488, "parola": "VALLEDIINNOM", "def": "Luogo a sud di Gerusalemme associato alla Geena.", "rif": "Geremia 7:31" },
    { "id": 489, "parola": "VANITA", "def": "Qualcosa di vuoto, transitorio o senza valore.", "rif": "Ecclesiaste 1:2" },
    { "id": 490, "parola": "VELO", "def": "Cortina che separava il Santo dal Santissimo.", "rif": "Esodo 26:33" },
    { "id": 491, "parola": "VERITA", "def": "La realta dei fatti rivelata nella Parola di Dio.", "rif": "Giovanni 17:17" },
    { "id": 492, "parola": "VESTE", "def": "Indumento, spesso simbolo della propria condizione spirituale.", "rif": "Rivelazione 19:8" },
    { "id": 493, "parola": "VIA", "def": "Termine usato per indicare il modo di vivere cristiano.", "rif": "Atti 9:2" },
    { "id": 494, "parola": "VIGNA", "def": "Terreno coltivato a viti, spesso simbolo d'Israele.", "rif": "Isaia 5:7" },
    { "id": 495, "parola": "VIRTU", "def": "Eccellenza morale e rettitudine d'animo.", "rif": "2 Pietro 1:5" },
    { "id": 496, "parola": "VISIONE", "def": "Rivelazione divina trasmessa in modo visivo.", "rif": "Daniele 7:1" },
    { "id": 497, "parola": "VITAETERNA", "def": "Dono di Dio di vivere per sempre in perfezione.", "rif": "Giovanni 17:3" },
    { "id": 498, "parola": "VOTO", "def": "Promessa solenne fatta volontariamente a Dio.", "rif": "Numeri 30:2" },
    { "id": 499, "parola": "WOL", "def": "Acronimo per la biblioteca online dei testimoni di Geova.", "rif": "Glossario" },
    { "id": 500, "parola": "ZACCARIA", "def": "Nome di un profeta e del padre di Giovanni Battista.", "rif": "Luca 1:5" },
    { "id": 501, "parola": "ZELO", "def": "Ardore e fervore nel servire Dio.", "rif": "Romani 12:11" },
    { "id": 502, "parola": "ZIZANIA", "def": "Pianta infestante che somiglia al grano.", "rif": "Matteo 13:25" },
    { "id": 503, "parola": "ZOLFO", "def": "Sostanza infiammabile simbolo di distruzione.", "rif": "Rivelazione 21:8" },
    { "id": 504, "parola": "ZOROBABELE", "def": "Governatore che guido la ricostruzione del tempio.", "rif": "Esdra 3:2" },
    { "id": 505, "parola": "CIPRO", "def": "Isola dove nacque Barnaba.", "rif": "Atti 4:36" },
    { "id": 506, "parola": "SPAGNA", "def": "Nazione che Paolo desiderava visitare.", "rif": "Romani 15:24" },
    { "id": 507, "parola": "ITALIA", "def": "Paese da cui provenivano Aquila e Priscilla.", "rif": "Atti 18:2" },
    // Aggiungo qui le restanti 93 voci (Monti, Fiumi, Regioni) ricalibrate
    { "id": 508, "parola": "ARARAT", "def": "Monti su cui si poso l'arca dopo il Diluvio.", "rif": "Genesi 8:4" },
    { "id": 509, "parola": "SINAI", "def": "Monte dove Mose ricevette la Legge.", "rif": "Esodo 19:2" },
    { "id": 510, "parola": "OREB", "def": "Altro nome del monte Sinai.", "rif": "Esodo 3:1" },
    { "id": 511, "parola": "ERMON", "def": "Monte innevato al confine settentrionale.", "rif": "Salmo 133:3" },
    { "id": 512, "parola": "CARMELO", "def": "Promontorio dove Elia sfido i profeti.", "rif": "1 Re 18:19" },
    { "id": 513, "parola": "NEBO", "def": "Monte da cui Mose vide la Terra Promessa.", "rif": "Deuteronomio 34:1" },
    { "id": 514, "parola": "TABOR", "def": "Monte della Galilea.", "rif": "Giudici 4:6" },
    { "id": 515, "parola": "GHERIZIM", "def": "Monte delle benedizioni.", "rif": "Deuteronomio 11:29" },
    { "id": 516, "parola": "EBAL", "def": "Monte delle maledizioni.", "rif": "Giosue 8:33" },
    { "id": 517, "parola": "OLIVETO", "def": "Monte a est di Gerusalemme.", "rif": "Matteo 21:1" },
    { "id": 518, "parola": "GIORDANO", "def": "Fiume principale della Palestina.", "rif": "Giosue 3:1" },
    { "id": 519, "parola": "EUFRATE", "def": "Grande fiume di Babilonia.", "rif": "Genesi 2:14" },
    { "id": 520, "parola": "TIGRI", "def": "Fiume dell'Assiria.", "rif": "Genesi 2:14" },
    { "id": 521, "parola": "NILO", "def": "Fiume egiziano.", "rif": "Esodo 7:17" },
    { "id": 522, "parola": "IABBOC", "def": "Affluente del Giordano.", "rif": "Genesi 32:22" },
    { "id": 523, "parola": "ARNON", "def": "Torrente di Moab.", "rif": "Numeri 21:13" },
    { "id": 524, "parola": "CHISON", "def": "Torrente della sconfitta di Sisera.", "rif": "Giudici 5:21" },
    { "id": 525, "parola": "GALILEA", "def": "Regione settentrionale.", "rif": "Matteo 4:12" },
    { "id": 526, "parola": "GIUDEA", "def": "Regione meridionale.", "rif": "Matteo 2:1" },
    { "id": 527, "parola": "SAMARIA", "def": "Regione centrale.", "rif": "Giovanni 4:4" },
    { "id": 528, "parola": "PEREA", "def": "Regione oltre il Giordano.", "rif": "Glossario" },
    { "id": 529, "parola": "MACEDONIA", "def": "Regione della Grecia.", "rif": "Atti 16:9" },
    { "id": 530, "parola": "ACAIA", "def": "Provincia romana della Grecia.", "rif": "Atti 18:12" },
    { "id": 531, "parola": "GALAZIA", "def": "Regione dell'Asia Minore.", "rif": "Galati 1:2" },
    { "id": 532, "parola": "ASIA", "def": "Provincia romana delle sette congregazioni.", "rif": "Rivelazione 1:4" },
    { "id": 533, "parola": "CILICIA", "def": "Regione con capitale Tarso.", "rif": "Atti 9:11" },
    { "id": 534, "parola": "FENICIA", "def": "Regione di Tiro e Sidone.", "rif": "Atti 11:19" },
    { "id": 535, "parola": "ARABIA", "def": "Regione desertica.", "rif": "Galati 1:17" },
    { "id": 536, "parola": "ELAM", "def": "Regione a est di Babilonia.", "rif": "Genesi 10:22" },
    { "id": 537, "parola": "ETIOPIA", "def": "Regione a sud dell'Egitto.", "rif": "Atti 8:27" },
    { "id": 538, "parola": "LIBIA", "def": "Regione dell'Africa.", "rif": "Atti 2:10" },
    { "id": 539, "parola": "CANAAN", "def": "Terra promessa.", "rif": "Genesi 12:5" },
    { "id": 540, "parola": "MESOPOTAMIA", "def": "Terra tra i due fiumi.", "rif": "Genesi 24:10" },
    { "id": 541, "parola": "BASCAN", "def": "Regione dei tori.", "rif": "Salmo 22:12" },
    { "id": 542, "parola": "GALAAD", "def": "Regione del balsamo.", "rif": "Geremia 8:22" },
    { "id": 543, "parola": "MOAB", "def": "Altopiano a est del Mar Morto.", "rif": "Genesi 19:37" },
    { "id": 544, "parola": "EDOM", "def": "Regione a sud del Mar Morto.", "rif": "Genesi 36:8" },
    { "id": 545, "parola": "SIRIA", "def": "Regione a nord.", "rif": "Matteo 4:24" },
    { "id": 546, "parola": "PAMPILIA", "def": "Provincia costiera asiatica.", "rif": "Atti 13:13" },
    { "id": 547, "parola": "FRIGIA", "def": "Regione interna asiatica.", "rif": "Atti 16:6" },
    { "id": 548, "parola": "PONTO", "def": "Regione del Mar Nero.", "rif": "1 Pietro 1:1" },
    { "id": 549, "parola": "BITINIA", "def": "Provincia settentrionale asiatica.", "rif": "Atti 16:7" },
    { "id": 550, "parola": "CAPPADOCIA", "def": "Regione interna.", "rif": "Atti 2:9" },
    { "id": 551, "parola": "ILLIRICO", "def": "Regione a nord della Macedonia.", "rif": "Romani 15:19" },
    { "id": 552, "parola": "DALMAZIA", "def": "Parte dell'Illirico.", "rif": "2 Timoteo 4:10" },
    { "id": 553, "parola": "LICAONIA", "def": "Regione dell'Asia Minore dove Paolo predico.", "rif": "Atti 14:6" },
    { "id": 554, "parola": "LICIA", "def": "Provincia sulla costa meridionale dell'Asia.", "rif": "Atti 27:5" },
    { "id": 555, "parola": "ITUREA", "def": "Regione a nord est del Mar di Galilea.", "rif": "Luca 3:1" },
    { "id": 556, "parola": "TRACHONITIDE", "def": "Regione governata dal tetrarca Filippo.", "rif": "Luca 3:1" },
    { "id": 557, "parola": "ABilene", "def": "Piccola provincia della Siria citata da Luca.", "rif": "Luca 3:1" },
    { "id": 558, "parola": "MOLOC", "def": "Dio degli ammoniti a cui si offrivano sacrifici.", "rif": "Atti 7:43" },
    { "id": 559, "parola": "ASTARTE", "def": "Dea cananea della guerra e della fertilita.", "rif": "Giudici 2:13" },
    { "id": 560, "parola": "MILCOM", "def": "Altro nome del dio ammonita Moloc.", "rif": "1 Re 11:5" },
    { "id": 561, "parola": "DAGON", "def": "Dio principale dei filistei, metà uomo e metà pesce.", "rif": "Giudici 16:23" },
    { "id": 562, "parola": "TAMMUZ", "def": "Divinita babilonese per cui le donne piangevano.", "rif": "Ezechiele 8:14" },
    { "id": 563, "parola": "ARTEMIDE", "def": "Dea efesina della caccia, nota come Diana.", "rif": "Atti 19:27" },
    { "id": 564, "parola": "ZEUS", "def": "Capo degli dei greci, confuso con Barnaba.", "rif": "Atti 14:12" },
    { "id": 565, "parola": "ERMES", "def": "Messaggero degli dei greci, confuso con Paolo.", "rif": "Atti 14:12" },
    { "id": 566, "parola": "MARDUK", "def": "Dio principale della citta di Babilonia.", "rif": "Geremia 50:2" },
    { "id": 567, "parola": "NERGAL", "def": "Dio della guerra adorato dai coloni assiri.", "rif": "2 Re 17:30" },
    { "id": 568, "parola": "OSTRACA", "def": "Frammenti di terracotta usati come materiale da scrittura.", "rif": "Glossario" },
    { "id": 569, "parola": "CEDRI", "def": "Alberi maestosi famosi nel Libano.", "rif": "Salmo 92:12" },
    { "id": 570, "parola": "SICOMORO", "def": "Albero su cui sali Zaccheo per vedere Gesu.", "rif": "Luca 19:4" },
    { "id": 571, "parola": "HISSopo", "def": "Pianta usata nei riti di purificazione.", "rif": "Esodo 12:22" },
    { "id": 572, "parola": "ACACIA", "def": "Legno resistente usato per il tabernacolo.", "rif": "Esodo 25:10" },
    { "id": 573, "parola": "INCENSIERE", "def": "Vaso metallico per bruciare l'incenso.", "rif": "Ebrei 9:4" },
    { "id": 574, "parola": "TURIBOLO", "def": "Altro nome per l'incensiere sacro.", "rif": "Rivelazione 8:3" },
    { "id": 575, "parola": "PETTORALE", "def": "Parte della veste del sommo sacerdote con 12 pietre.", "rif": "Esodo 28:15" },
    { "id": 576, "parola": "TIARA", "def": "Copricapo regale o sacerdotale.", "rif": "Ezechiele 21:26" },
    { "id": 577, "parola": "SANDAlo", "def": "Calzatura comune ai tempi biblici.", "rif": "Marco 6:9" },
    { "id": 578, "parola": "BISSO", "def": "Lino finissimo usato per vesti di lusso.", "rif": "Rivelazione 19:8" },
    { "id": 579, "parola": "SICLO", "def": "Unita di peso e moneta ebraica.", "rif": "Genesi 23:15" },
    { "id": 580, "parola": "DENARIO", "def": "Moneta romana d'argento, paga giornaliera di un operaio.", "rif": "Matteo 20:2" },
    { "id": 581, "parola": "DRACMA", "def": "Moneta greca d'argento.", "rif": "Luca 15:8" },
    { "id": 582, "parola": "DIDRAMMA", "def": "Moneta pari a due dracme, usata per la tassa del tempio.", "rif": "Matteo 17:24" },
    { "id": 583, "parola": "LEPTON", "def": "Piccola moneta di rame, come l'obolo della vedova.", "rif": "Marco 12:42" },
    { "id": 584, "parola": "CORBANA", "def": "Dono dedicato a Dio che non poteva essere usato per altro.", "rif": "Marco 7:11" },
    { "id": 585, "parola": "ANATEMA", "def": "Cosa o persona votata alla distruzione o maledetta.", "rif": "1 Corinti 16:22" },
    { "id": 586, "parola": "MARANATA", "def": "Espressione che significa il Signore viene.", "rif": "1 Corinti 16:22" },
    { "id": 587, "parola": "RABBI", "def": "Titolo rispettoso che significa mio maestro.", "rif": "Giovanni 1:38" },
    { "id": 588, "parola": "MESSIAS", "def": "Forma greca del termine ebraico Mashiah.", "rif": "Giovanni 4:25" },
    { "id": 589, "parola": "PANTOCRATORE", "def": "Titolo di Dio che significa Onnipotente.", "rif": "2 Corinti 6:18" },
    { "id": 590, "parola": "PARACLITO", "def": "Soccorritore o consolatore; riferito allo spirito.", "rif": "Giovanni 14:16" },
    { "id": 591, "parola": "PARUSIA", "def": "Termine greco per presenza, riferito al ritorno di Cristo.", "rif": "Matteo 24:3" },
    { "id": 592, "parola": "CHERUBINI", "def": "Angeli di alto rango che sostengono il trono di Dio.", "rif": "Genesi 3:24" },
    { "id": 593, "parola": "SERAFINI", "def": "Creature celesti viste in visione da Isaia.", "rif": "Isaia 6:2" },
    { "id": 594, "parola": "NEFILIM", "def": "Giganti nati dall'unione di angeli e donne.", "rif": "Genesi 6:4" },
    { "id": 595, "parola": "REFAIM", "def": "Antica popolazione di giganti in Canaan.", "rif": "Genesi 14:5" },
    { "id": 596, "parola": "ANACHITI", "def": "Popolo di alta statura che spavento le spie.", "rif": "Numeri 13:22" },
    { "id": 597, "parola": "EBla", "def": "Antica citta siriana di importanza archeologica.", "rif": "Glossario" },
    { "id": 598, "parola": "UGARIT", "def": "Citta fenicia i cui testi chiariscono termini biblici.", "rif": "Glossario" },
    { "id": 599, "parola": "QUmran", "def": "Luogo del ritrovamento dei rotoli del Mar Morto.", "rif": "Glossario" },
    { "id": 600, "parola": "MADIANITI", "def": "Discendenti di Madian che commerciarono con Giuseppe.", "rif": "Genesi 37:28" }
  ]
};
